Update phpquickprofiler.php
Include once directive was added.
Fatal error: Call to undefined function displayPqp() in /var/www/clients/client0/web1/private/fuelphp-1.7.1/fuel/core/vendor/phpquickprofiler/phpquickprofiler.php on line 226